spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=never

mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.banner=false

myhotel.room-number.min-floor=${MYHOTEL_ROOM_MIN_FLOOR:8}
myhotel.room-number.max-floor=${MYHOTEL_ROOM_MAX_FLOOR:19}
myhotel.room-number.max-room-per-floor=${MYHOTEL_ROOM_MAX_ROOM_PER_FLOOR:20}
